spring:
  rabbitmq:
    host: rabbitmq
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: simple-service
          uri: lb://simple-service
          predicates:
            - Path=/simple/**
          filters:
            - RewritePath=/simple/(?<path>.*), /$\{path}
        - id: eureka-server
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
